### PR TITLE
Added app sections support, corrected header buttons, added support for SensorTag 2

### PR DESCRIPTION
**Pull request by Sionarch**
BLE Scan example: Added menu alternatives 'Troubleshooting' and 'Home'.

### CODE REVIEW

**Comment by Sionarch** [comment]
FastClick library might be replaced by smaller library included in util.js.

**Comment by fredrikeldh** [comment]
I've got some problems with a SensorTag 2 (firmware 0.8):
* IR temperature reports about +70 °C while ambient is a more normal 23 °C.
* Barometer is [Waiting for value].
* Luxometer is [Waiting for value].

**Comment by Sionarch** [comment]
Confirmed previously mentioned issues. There are differences between the (beta) firmware versions of the SensorTag 2. It seems to matter which sensors are activated concurrently. Investigation ongoing...

**Comment by Sionarch** [comment]
The issue regarding that the barometer and luxometer values are not displayed occurs on FW rev 0.89+.

**Comment by Sionarch** [comment]
SensorTag 2 FW 0.89 seems to be buggy. Even in TIs own app the movement notifications and luxometer notifications don't run at the same time. It works using FW 0.87E.

**Pull request merged**
