### PR TITLE
sensortag.js: added barometer calibration procedure and pressure calculations for the SensorTag 1.

### PR DESCRIPTION
**Pull request by Sionarch**
The Callback Pyramid of Doom is looming, but it works ;)

### CODE REVIEW

**Comment by fredrikeldh** [comment]
Needs to be rebased on #136.

**Comment by manta103g** [comment]
https://github.com/evothings/evothings-examples/tree/master/examples/hue-lights

Hi Eric,

just trying to learn how to communicate with a developer like you on GitHub since no option for discussions.
So this link looks to be an only option to ask you just few questions.

Let me know if examples can be downloaded since no zip download link available
and the above page opens oversized, not fit for 10" screen , so right margin is cuf off.

This page
https://github.com/evothings/HyperReload
opens as full website and ZIP Download link is present

Let me know how to run your apps on Android (still not rooted):
zip download, 7-zip unpacked into demo1 directory and open html file in web browser ?
or I need to download js library mentioned by you.

Node-webkit just turned to nw.js (https://github.com/nwjs/nw.js  redirected)
Is this the right runtime for your app code ?

I leave my email contact in case I am lost to follow this thread on GitHub

thanks
darius
manta103g@gmail.com
I am just looking at js examples for Android machine (my tablet is 10" Android)

**Comment by divineprog** [comment]
@manta103g Hi Darius, download Evothings Studio and use that instead of HyperReload. Here it is: http://evothings.com

**Comment by manta103g** [comment]
Thank you Fredrik,

another option available to me to test HTML5 + Philips Hue is
Chrome extension (crx)

one is called Lightswitch

http://www.developers.meethue.com/content/lightswitch-philips-hue-%E2%80%94-windows-mac-linux-chromebooks-chrome-extension

The issue is I don't run Chrome on old PC Windows XP machine, running
Philips Hue API Emulator for Windows by Steve (off-line mode).

Tell me how complicated is to develop basic HTML5 demo with the Studio and
if curl library is supported to send PUT, GET calls to Philips Hue API
server
and get callsbacks parsed to update HTML5 GUI (sliders, Hue lights
graphics).

darius

2015-04-10 14:24 GMT+02:00 Fredrik Eldh <notifications@github.com>:

**Comment by fredrikeldh** [comment]
Darius, off-topic posts are not allowed on this issue tracker. Please use the [Evothings forum](http://evothings.com/forum/) instead. Any further off-topic posts will be deleted.

**Pull request merged**
